package telas;

import java.io.File;
import java.nio.file.Files;
import javax.swing.JFileChooser;
import classes.Animal;
import classes.Cliente;
import classes.Usuario;
import java.time.format.DateTimeFormatter;
import dao.AnimalDAO;
import dao.ClienteDAO;
import dao.OrigemDestinoDAO;
import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import permissoes.Sessao;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author bello
 */
public class TelaAnimal extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaAnimal.class.getName());

    private Animal animal = new Animal();
    private List<Cliente> listaClientes = new ArrayList<>();
    private boolean editando = false;
    private int idAtual = 0;

    public TelaAnimal() {
        initComponents();
        limparCampos();
        carregarCombos();
    }

    Usuario usuario = Sessao.getUsuario();

    public void limparCampos() {
        txtNome.setText("");
        txtRaca.setText("");
        txtPeso.setText("");
        txtCor.setText("");
        txtData.setText("");
        cmbTamanho.setSelectedIndex(0);
        cmbCaixa.setSelectedIndex(0);
        txtMicrochip.setText("");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        lblNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        lblRaca = new javax.swing.JLabel();
        txtRaca = new javax.swing.JTextField();
        lblCor = new javax.swing.JLabel();
        txtCor = new javax.swing.JTextField();
        lblPeso = new javax.swing.JLabel();
        txtPeso = new javax.swing.JTextField();
        lblCaixa = new javax.swing.JLabel();
        txtMicrochip = new javax.swing.JTextField();
        lblMicrochip = new javax.swing.JLabel();
        lblTamanho = new javax.swing.JLabel();
        lblData = new javax.swing.JLabel();
        lblCarteirinha = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btnCarteirinha = new javax.swing.JButton();
        lblDocumentos = new javax.swing.JLabel();
        btnDocumentos = new javax.swing.JButton();
        lblImagens = new javax.swing.JLabel();
        btnImagens = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        btnLista = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        txtData = new javax.swing.JTextField();
        cmbTamanho = new javax.swing.JComboBox<>();
        cmbCaixa = new javax.swing.JComboBox<>();
        lblCliente = new javax.swing.JLabel();
        cmbCliente = new javax.swing.JComboBox<>();
        btnAtualizar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("PETCARGO");

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        lblNome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNome.setText("Nome:");
        lblNome.setToolTipText("Nome do pet");
        lblNome.setOpaque(true);

        txtNome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNome.setToolTipText("Digitar nome do pet");
        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });

        lblRaca.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblRaca.setText("Raça:");
        lblRaca.setToolTipText("Raça do pet");
        lblRaca.setOpaque(true);

        txtRaca.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtRaca.setToolTipText("Digitar raça do pet");

        lblCor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCor.setText("Cor:");
        lblCor.setToolTipText("Cor do pet");
        lblCor.setOpaque(true);

        txtCor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtCor.setToolTipText("Digitar cor do pet");

        lblPeso.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblPeso.setText("Peso:");
        lblPeso.setToolTipText("Peso do pet");
        lblPeso.setOpaque(true);

        txtPeso.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtPeso.setToolTipText("Digitar peso do pet");

        lblCaixa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCaixa.setText("Caixa de Transporte:");
        lblCaixa.setToolTipText("Tamanho da caixa de transporte");
        lblCaixa.setOpaque(true);

        txtMicrochip.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtMicrochip.setToolTipText("Digitar número do microchip do pet");

        lblMicrochip.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblMicrochip.setText("Microchip:");
        lblMicrochip.setToolTipText("Número do microchip do pet");
        lblMicrochip.setOpaque(true);

        lblTamanho.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTamanho.setText("Tamanho:");
        lblTamanho.setToolTipText("Tamanho do pet");
        lblTamanho.setOpaque(true);

        lblData.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblData.setText("Data de Nascimento:");
        lblData.setToolTipText("Data de nascimento do pet");
        lblData.setOpaque(true);

        lblCarteirinha.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCarteirinha.setText("Carteirinha:");
        lblCarteirinha.setToolTipText("Carteirinha de vacina do pet");
        lblCarteirinha.setOpaque(true);

        jLabel11.setBackground(new java.awt.Color(102, 204, 255));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel11.setText("Informações do PET");
        jLabel11.setOpaque(true);

        btnCarteirinha.setText("SELECIONAR");
        btnCarteirinha.setToolTipText("Selecionar imagem da carteirinha de vacina do pet");
        btnCarteirinha.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCarteirinha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarteirinhaActionPerformed(evt);
            }
        });

        lblDocumentos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDocumentos.setText("Documentos:");
        lblDocumentos.setToolTipText("Documentos do pet");
        lblDocumentos.setOpaque(true);

        btnDocumentos.setText("SELECIONAR");
        btnDocumentos.setToolTipText("Selecionar documentos do pet");
        btnDocumentos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnDocumentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDocumentosActionPerformed(evt);
            }
        });

        lblImagens.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblImagens.setText("Imagens:");
        lblImagens.setToolTipText("Imagens do pet");
        lblImagens.setOpaque(true);

        btnImagens.setText("SELECIONAR");
        btnImagens.setToolTipText("Selecionar imagens do pet");
        btnImagens.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnImagens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImagensActionPerformed(evt);
            }
        });

        btnSalvar.setBackground(new java.awt.Color(102, 255, 102));
        btnSalvar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSalvar.setText("SALVAR");
        btnSalvar.setToolTipText("Salvar os dados escritos");
        btnSalvar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnLimpar.setBackground(new java.awt.Color(255, 255, 0));
        btnLimpar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLimpar.setText("LIMPAR DADOS");
        btnLimpar.setToolTipText("Apagar dados escritos");
        btnLimpar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        btnLista.setBackground(new java.awt.Color(102, 255, 255));
        btnLista.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLista.setText("LISTA DOS ANIMAIS");
        btnLista.setToolTipText("Navega até a lista de animais");
        btnLista.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListaActionPerformed(evt);
            }
        });

        btnVoltar.setBackground(new java.awt.Color(153, 153, 255));
        btnVoltar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnVoltar.setText("VOLTAR");
        btnVoltar.setToolTipText("Voltar até tela inicial");
        btnVoltar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        txtData.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtData.setToolTipText("Digitar data de nascimento do pet");

        cmbTamanho.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmbTamanho.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pequeno porte", "Medio porte", "Grande porte" }));
        cmbTamanho.setToolTipText("Escolher qual o tamanho do pet");
        cmbTamanho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTamanhoActionPerformed(evt);
            }
        });

        cmbCaixa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmbCaixa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Caixa 200", "Caixa 300", "Caixa 400", "Caixa 500", "Caixa 700" }));
        cmbCaixa.setToolTipText("Escolher qual caixa e mais adequada para o tamanho do pet");

        lblCliente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCliente.setText("Cliente:");
        lblCliente.setToolTipText("Nome do cliente");
        lblCliente.setOpaque(true);

        cmbCliente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmbCliente.setToolTipText("Buscar cliente associado a pet");

        btnAtualizar.setBackground(new java.awt.Color(255, 0, 255));
        btnAtualizar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAtualizar.setText("ATUALIZAR");
        btnAtualizar.setToolTipText("Salvar os dados escritos");
        btnAtualizar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblMicrochip, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMicrochip, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblTamanho, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbTamanho, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cmbCaixa, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cmbCliente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblCarteirinha, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnCarteirinha)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(79, 79, 79)
                                        .addComponent(lblDocumentos, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnDocumentos)
                                        .addGap(85, 85, 85)
                                        .addComponent(lblImagens, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnImagens))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(20, 20, 20)
                                        .addComponent(btnAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(20, 20, 20)
                                        .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(lblRaca, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(lblNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtRaca, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(39, 39, 39)
                                        .addComponent(lblCor, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtCor, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(31, 31, 31)
                                        .addComponent(lblData, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtData))))
                            .addComponent(txtNome))))
                .addGap(20, 20, 20))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(175, 175, 175)
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLista)
                .addGap(278, 278, 278))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel11)
                .addGap(28, 28, 28)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNome))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRaca)
                    .addComponent(lblCor)
                    .addComponent(txtCor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPeso)
                    .addComponent(txtRaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMicrochip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMicrochip)
                    .addComponent(lblData)
                    .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTamanho)
                    .addComponent(lblCaixa)
                    .addComponent(cmbTamanho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCarteirinha)
                    .addComponent(btnCarteirinha)
                    .addComponent(lblDocumentos)
                    .addComponent(btnDocumentos)
                    .addComponent(lblImagens)
                    .addComponent(btnImagens))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCliente)
                    .addComponent(cmbCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar)
                    .addComponent(btnLimpar)
                    .addComponent(btnVoltar)
                    .addComponent(btnAtualizar))
                .addGap(35, 35, 35)
                .addComponent(btnLista)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        jMenu1.setBackground(new java.awt.Color(0, 0, 255));
        jMenu1.setText("MENU");
        jMenu1.setToolTipText("Menu de atalhos");
        jMenu1.setOpaque(true);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Z, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem1.setBackground(new java.awt.Color(153, 153, 255));
        jMenuItem1.setText("Voltar");
        jMenuItem1.setToolTipText("Voltar para escolha de classes");
        jMenuItem1.setOpaque(true);
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem2.setBackground(new java.awt.Color(255, 51, 51));
        jMenuItem2.setText("Sair");
        jMenuItem2.setToolTipText("Fechar a janela");
        jMenuItem2.setOpaque(true);
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void btnCarteirinhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarteirinhaActionPerformed
        try {
            JFileChooser fc = new JFileChooser();

            FileNameExtensionFilter filtro = new FileNameExtensionFilter(
                    "Arquivos PDF e Imagens", "pdf", "jpg", "png"
            );
            fc.setFileFilter(filtro);

            int res = fc.showOpenDialog(null);

            if (res == JFileChooser.APPROVE_OPTION) {
                File file = fc.getSelectedFile();

                byte[] dados = Files.readAllBytes(file.toPath());

                animal.setCarteirinha(dados);

                lblCarteirinha.setText(file.getName());
            }

        } catch (IOException ex) {
            System.out.println("Erro ao ler arquivo: " + ex.getMessage());
        }

    }//GEN-LAST:event_btnCarteirinhaActionPerformed

    private void btnDocumentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDocumentosActionPerformed
        try {
            JFileChooser fc = new JFileChooser();

            FileNameExtensionFilter filtro = new FileNameExtensionFilter(
                    "Arquivos PDF e Imagens", "pdf", "jpg", "png"
            );
            fc.setFileFilter(filtro);

            int res = fc.showOpenDialog(null);

            if (res == JFileChooser.APPROVE_OPTION) {
                File file = fc.getSelectedFile();

                byte[] dados = Files.readAllBytes(file.toPath());

                animal.setDocumentos(dados);

                lblDocumentos.setText(file.getName());
            }

        } catch (IOException ex) {
            System.out.println("Erro ao ler arquivo: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnDocumentosActionPerformed

    private void btnImagensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImagensActionPerformed
        try {
            JFileChooser fc = new JFileChooser();

            FileNameExtensionFilter filtro = new FileNameExtensionFilter(
                    "Arquivos PDF e Imagens", "pdf", "jpg", "png"
            );
            fc.setFileFilter(filtro);

            int res = fc.showOpenDialog(null);

            if (res == JFileChooser.APPROVE_OPTION) {
                File file = fc.getSelectedFile();

                byte[] dados = Files.readAllBytes(file.toPath());

                animal.setImagens(dados);

                lblImagens.setText(file.getName());
            }

        } catch (IOException ex) {
            System.out.println("Erro ao ler arquivo: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnImagensActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        new TelaClasses(usuario).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        limparCampos();
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed

        try {
            AnimalDAO dao = new AnimalDAO();

            //  VALIDAÇÃO GERAL (ANTES DE TUDO)
            if (txtNome.getText().isEmpty()
                    || txtRaca.getText().isEmpty()
                    || txtCor.getText().isEmpty()
                    || txtPeso.getText().isEmpty()
                    || txtMicrochip.getText().isEmpty()
                    || txtData.getText().isEmpty()
                    || cmbCliente.getSelectedIndex() == -1) {

                JOptionPane.showMessageDialog(null, "Preencha TODOS os campos!");
                return;
            }

            //  SET BÁSICO
            animal.setNome(txtNome.getText());
            animal.setRaca(txtRaca.getText());
            animal.setCor(txtCor.getText());
            animal.setMicrochip(txtMicrochip.getText());

            //  PESO (CORRIGIDO)
            try {
                animal.setPeso(Double.parseDouble(txtPeso.getText()));
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Peso inválido!");
                return;
            }

            //  TAMANHO
            String tamanho = cmbTamanho.getSelectedItem().toString();

            switch (tamanho) {
                case "Pequeno porte":
                    animal.setTamanho(1);
                    break;
                case "Medio porte":
                    animal.setTamanho(2);
                    break;
                case "Grande porte":
                    animal.setTamanho(3);
                    break;
            }

            //  CAIXA
            String caixa = cmbCaixa.getSelectedItem().toString();
            int numeroCaixa = Integer.parseInt(caixa.replace("Caixa ", ""));
            animal.setCaixaTransporte(numeroCaixa);

            //  DATA (COM RETURN NO ERRO)
            try {
                String dataTexto = txtData.getText();

                java.time.format.DateTimeFormatter formatter
                        = java.time.format.DateTimeFormatter.ofPattern("dd/MM/yyyy");

                java.time.LocalDate data
                        = java.time.LocalDate.parse(dataTexto, formatter);

                animal.setDataNascimento(data);

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Data inválida! Use dd/MM/yyyy");
                return;
            }

            // ? CLIENTE
            int indexCliente = cmbCliente.getSelectedIndex();
            Cliente clienteSelecionado = listaClientes.get(indexCliente);

            animal.setCliente(clienteSelecionado);

            if (editando) {

                animal.setIdAnimal(idAtual);
                dao.atualizar(animal);

                JOptionPane.showMessageDialog(null, "Origem e destino atualizado com sucesso!");

            } else {

                dao.inserir(animal);

                JOptionPane.showMessageDialog(null, "Origem e destino salvo com sucesso!");
            }

            limparCampos();

            // RESETAR MODO
            editando = false;
            idAtual = 0;
            btnSalvar.setEnabled(true);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao salvar: " + e.getMessage());
        }


    }//GEN-LAST:event_btnSalvarActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        new TelaClasses(usuario).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
        try {
            AnimalDAO dao = new AnimalDAO();

            // VALIDAÇÃO
            if (txtNome.getText().isEmpty()
                    || txtRaca.getText().isEmpty()
                    || txtCor.getText().isEmpty()
                    || txtPeso.getText().isEmpty()
                    || txtMicrochip.getText().isEmpty()
                    || txtData.getText().isEmpty()
                    || cmbCliente.getSelectedIndex() == -1) {

                JOptionPane.showMessageDialog(null, "Preencha TODOS os campos!");
                return;
            }

            Animal a = new Animal();

            a.setIdAnimal(idAtual); // ? IMPORTANTE

            a.setNome(txtNome.getText());
            a.setRaca(txtRaca.getText());
            a.setCor(txtCor.getText());
            a.setMicrochip(txtMicrochip.getText());

            // PESO
            a.setPeso(Double.parseDouble(txtPeso.getText()));

            // TAMANHO
            String tamanho = cmbTamanho.getSelectedItem().toString();

            switch (tamanho) {
                case "Pequeno porte":
                    animal.setTamanho(1);
                    break;
                case "Medio porte":
                    animal.setTamanho(2);
                    break;
                case "Grande porte":
                    animal.setTamanho(3);
                    break;
            }

            // CAIXA
            String caixa = cmbCaixa.getSelectedItem().toString();
            int numeroCaixa = Integer.parseInt(caixa.replace("Caixa ", ""));
            a.setCaixaTransporte(numeroCaixa);

            // DATA
            java.time.format.DateTimeFormatter formatter
                    = java.time.format.DateTimeFormatter.ofPattern("dd/MM/yyyy");

            a.setDataNascimento(
                    java.time.LocalDate.parse(txtData.getText(), formatter)
            );

            // CLIENTE
            Cliente clienteSelecionado = listaClientes.get(cmbCliente.getSelectedIndex());
            a.setCliente(clienteSelecionado);

            // ATUALIZAR
            dao.atualizar(a);

            JOptionPane.showMessageDialog(null, "Animal atualizado com sucesso!");

            limparCampos();

            editando = false;
            idAtual = 0;
            btnSalvar.setEnabled(true);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao atualizar: " + e.getMessage());
        }

    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void btnListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListaActionPerformed
        ListaAnimal fre = new ListaAnimal();

        fre.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnListaActionPerformed

    private void cmbTamanhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTamanhoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbTamanhoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaAnimal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnCarteirinha;
    private javax.swing.JButton btnDocumentos;
    private javax.swing.JButton btnImagens;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnLista;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JComboBox<String> cmbCaixa;
    private javax.swing.JComboBox<String> cmbCliente;
    private javax.swing.JComboBox<String> cmbTamanho;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblCaixa;
    private javax.swing.JLabel lblCarteirinha;
    private javax.swing.JLabel lblCliente;
    private javax.swing.JLabel lblCor;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblDocumentos;
    private javax.swing.JLabel lblImagens;
    private javax.swing.JLabel lblMicrochip;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblPeso;
    private javax.swing.JLabel lblRaca;
    private javax.swing.JLabel lblTamanho;
    private javax.swing.JTextField txtCor;
    private javax.swing.JTextField txtData;
    private javax.swing.JTextField txtMicrochip;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtPeso;
    private javax.swing.JTextField txtRaca;
    // End of variables declaration//GEN-END:variables

    public void setAnimal(Animal a) {
        txtNome.setText(a.getNome());
        txtRaca.setText(a.getRaca());
        txtCor.setText(a.getCor());
        txtPeso.setText(String.valueOf(a.getPeso()));
        txtMicrochip.setText(a.getMicrochip());

        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");

        if (a.getDataNascimento() != null) {
            txtData.setText(a.getDataNascimento().format(formatter));
        }

        switch (a.getTamanho()) {
            case 1:
                cmbTamanho.setSelectedItem("Pequeno porte");
                break;
            case 2:
                cmbTamanho.setSelectedItem("Medio porte");
                break;
            case 3:
                cmbTamanho.setSelectedItem("Grande porte");
                break;
            default:
                cmbTamanho.setSelectedIndex(0);
        }

        // CAIXA
        cmbCaixa.setSelectedItem("Caixa " + a.getCaixaTransporte());

        // CLIENTE
        for (int i = 0; i < listaClientes.size(); i++) {
            if (listaClientes.get(i).getIdCliente() == a.getCliente().getIdCliente()) {
                cmbCliente.setSelectedIndex(i);
                break;
            }
        }

        idAtual = a.getIdAnimal();
        editando = true;

        btnSalvar.setEnabled(false);
    }

    private void carregarCombos() {

        try {
            ClienteDAO clienteDAO = new ClienteDAO();
            OrigemDestinoDAO odDAO = new OrigemDestinoDAO();

            // limpa antes
            cmbCliente.removeAllItems();

            // ? CLIENTES
            listaClientes = clienteDAO.listar();

            for (Cliente c : listaClientes) {
                cmbCliente.addItem(c.getNome());
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao carregar combos: " + e.getMessage());
        }
    }

}
