package telas;

import classes.Usuario;
import dao.UsuarioDAO;
import permissoes.Permissao;
import permissoes.PermissaoUsuarios;

/**
 *
 * @author bello
 */
public class TelaClasses extends javax.swing.JFrame {

    private Permissao permissao;
    private Usuario usuario; // usuário logado
    private UsuarioDAO dao;

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaClasses.class.getName());

    private void aplicarPermissoes() {

        btnAnimal.setEnabled(permissao.podeAnimal());
        btnCliente.setEnabled(permissao.podeCliente());
        btnEndereco.setEnabled(permissao.podeEndereco());
        btnFinanceiro.setEnabled(permissao.podeFinanceiro());
        btnOrigem.setEnabled(permissao.podeOrigem());
        btnTaxi.setEnabled(permissao.podeTaxi());
        btnVacina.setEnabled(permissao.podeVacina());
    }

    public TelaClasses(Usuario usuario) {
        initComponents();

        this.usuario = usuario;
        dao = new UsuarioDAO();
        permissao = PermissaoUsuarios.getPermissao(usuario.getTipo());

        aplicarPermissoes();

    }

    public TelaClasses() {
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnAnimal = new javax.swing.JButton();
        btnCliente = new javax.swing.JButton();
        btnEndereco = new javax.swing.JButton();
        btnFinanceiro = new javax.swing.JButton();
        btnOrigem = new javax.swing.JButton();
        btnTaxi = new javax.swing.JButton();
        btnVacina = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mniVoltar = new javax.swing.JMenuItem();
        mniSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PETCARGO");

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        jLabel1.setBackground(new java.awt.Color(51, 51, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("PETCARGO");
        jLabel1.setOpaque(true);

        btnAnimal.setBackground(new java.awt.Color(102, 255, 255));
        btnAnimal.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnAnimal.setText("Animal");
        btnAnimal.setToolTipText("Botão para ser direcionado a tabela de animal");
        btnAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnimalActionPerformed(evt);
            }
        });

        btnCliente.setBackground(new java.awt.Color(102, 255, 255));
        btnCliente.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnCliente.setText("Cliente");
        btnCliente.setToolTipText("Botão para ser direcionado a tabela de cliente");
        btnCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClienteActionPerformed(evt);
            }
        });

        btnEndereco.setBackground(new java.awt.Color(102, 255, 255));
        btnEndereco.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnEndereco.setText("Endereço");
        btnEndereco.setToolTipText("Botão para ser direcionado a tabela de endereço");
        btnEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnderecoActionPerformed(evt);
            }
        });

        btnFinanceiro.setBackground(new java.awt.Color(102, 255, 255));
        btnFinanceiro.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnFinanceiro.setText("Financeiro");
        btnFinanceiro.setToolTipText("Botão para ser direcionado a tabela de financeiro");
        btnFinanceiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinanceiroActionPerformed(evt);
            }
        });

        btnOrigem.setBackground(new java.awt.Color(102, 255, 255));
        btnOrigem.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnOrigem.setText("OrigemDestino");
        btnOrigem.setToolTipText("Botão para ser direcionado a tabela de origem e destino");
        btnOrigem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrigemActionPerformed(evt);
            }
        });

        btnTaxi.setBackground(new java.awt.Color(102, 255, 255));
        btnTaxi.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnTaxi.setText("Taxi");
        btnTaxi.setToolTipText("Botão para ser direcionado a tabela de taxi");
        btnTaxi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaxiActionPerformed(evt);
            }
        });

        btnVacina.setBackground(new java.awt.Color(102, 255, 255));
        btnVacina.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnVacina.setText("Vacina");
        btnVacina.setToolTipText("Botão para ser direcionado a tabela de vacina");
        btnVacina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVacinaActionPerformed(evt);
            }
        });

        btnVoltar.setBackground(new java.awt.Color(255, 255, 0));
        btnVoltar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnVoltar.setText("VOLTAR");
        btnVoltar.setToolTipText("Voltar até a tela de login");
        btnVoltar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(83, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(68, 68, 68))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnAnimal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnVacina, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnOrigem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnFinanceiro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEndereco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnTaxi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnVoltar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(83, 83, 83))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addGap(40, 40, 40)
                .addComponent(btnAnimal)
                .addGap(40, 40, 40)
                .addComponent(btnVacina)
                .addGap(40, 40, 40)
                .addComponent(btnCliente)
                .addGap(40, 40, 40)
                .addComponent(btnEndereco)
                .addGap(40, 40, 40)
                .addComponent(btnFinanceiro)
                .addGap(40, 40, 40)
                .addComponent(btnOrigem)
                .addGap(40, 40, 40)
                .addComponent(btnTaxi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(btnVoltar))
        );

        jMenu1.setBackground(new java.awt.Color(51, 51, 255));
        jMenu1.setText("MENU");
        jMenu1.setToolTipText("Menu de atalhos");
        jMenu1.setOpaque(true);

        mniVoltar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Z, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniVoltar.setBackground(new java.awt.Color(153, 153, 255));
        mniVoltar.setText("Voltar");
        mniVoltar.setToolTipText("Voltar para tela de login");
        mniVoltar.setOpaque(true);
        mniVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniVoltarActionPerformed(evt);
            }
        });
        jMenu1.add(mniVoltar);

        mniSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniSair.setBackground(new java.awt.Color(255, 51, 51));
        mniSair.setText("Sair");
        mniSair.setToolTipText("Fechar a janela");
        mniSair.setOpaque(true);
        mniSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniSairActionPerformed(evt);
            }
        });
        jMenu1.add(mniSair);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnimalActionPerformed
        TelaAnimal fre = new TelaAnimal();
        //Mostrando o form quando clicar no botão
        fre.setVisible(true);
    }//GEN-LAST:event_btnAnimalActionPerformed

    private void btnClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnClienteActionPerformed

    private void btnEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEnderecoActionPerformed

    private void btnFinanceiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinanceiroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFinanceiroActionPerformed

    private void btnOrigemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrigemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOrigemActionPerformed

    private void btnTaxiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaxiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTaxiActionPerformed

    private void btnVacinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVacinaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVacinaActionPerformed

    private void mniSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mniSairActionPerformed

    private void mniVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniVoltarActionPerformed
        Login fre = new Login();

        fre.setVisible(true);

    }//GEN-LAST:event_mniVoltarActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        Login fre = new Login();

        fre.setVisible(true);
    }//GEN-LAST:event_btnVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            Usuario u = new Usuario();
            u.setTipo("Gerente"); // teste
            new TelaClasses(u).setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnimal;
    private javax.swing.JButton btnCliente;
    private javax.swing.JButton btnEndereco;
    private javax.swing.JButton btnFinanceiro;
    private javax.swing.JButton btnOrigem;
    private javax.swing.JButton btnTaxi;
    private javax.swing.JButton btnVacina;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem mniSair;
    private javax.swing.JMenuItem mniVoltar;
    // End of variables declaration//GEN-END:variables
}
